version: "3.9"

services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_practice_php
    volumes:
      - ./:/var/www/html:cached
    environment:
      PHP_IDE_CONFIG: "serverName=symfony-practice.local"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony_practice_nginx
    depends_on:
      - php
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro