parameters: {}
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # === Factory method ===
    App\GofPatterns\Application\Console\FactoryMethodCommand: ~
    App\GofPatterns\Infrastructure\FactoryMethod\NotifierFactory: ~
    App\GofPatterns\Domain\FactoryMethod\NotifierFactoryInterface:
        alias: App\GofPatterns\Infrastructure\FactoryMethod\NotifierFactory
